### ISSUE TITLE
FSE Application - FSE Details - Inspection Frequency

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#1]
Issue:  On initial load of the screen (before edits are made) the label still reads "Inspection Frequency(days)".  It should read: "Inspection Frequency (months)."  Also, the slider should range all the way to 36.

![image](https://f.cloud.github.com/assets/5805454/2009046/e47563e2-8757-11e3-93d8-e560ce29f523.png)

Resolution: Please update the label and make the slider max-out at 36.

**Comment by kanglu666** [comment]
test at KCi version
http://dashboard.kci.com/fogservicesnew/index.html

**Comment by JMurk** [comment]
Confirmed complete @ KCI
