### ISSUE TITLE
FSE Application - FSE Report - Cleaning Frequency

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#12]
Issue:  Under GCD Inspection Details, the Cleaning Frequency field displays the coded value.

![image](https://f.cloud.github.com/assets/5805454/2009897/18f7dc68-8766-11e3-8d52-3452444f85f5.png)

Resolution: Display the domain's description value  (Eric, is this feasible?)

**Comment by tarheelgis** [comment]
Right now we have the following values. I could just do a replace at the time of query to remove the underscores?
3_Months
6_Weekly
Daily
Monthly
Weekly

**Comment by tarheelgis** [comment]
Went ahead and just put the replace in place and it works fine.
