### ISSUE TITLE
FSE Application - Inspections - Inspector ID

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#14]
Issue:  Currently there are fields in the UI for Inspector ID.  Nothing is ever populated in theses, particularly because there is no such ID.

![image](https://f.cloud.github.com/assets/5805454/2010047/73dac72e-8768-11e3-9e22-e5d7ec0ec152.png)

Resolution:  Change Inspector ID to Inspector Name (will likely need to update DB schema) and auto-populate this field with the username of the logged in user.  This should be populated on INSERT ONLY and never updated.

**Once this is complete, please assign to Eric so that the report can be updated to read Inspector Name rather than Inspector ID.

**Comment by kanglu666** [comment]
currently, there is no Inspector Name field in database. Inspector ID is the original design.
so we need to make the database schema change. any updates with db schema change will take some time.
and yes, we can give the current log in user name to populate the Inspector Name field.

**Comment by JMurk** [comment]
Per discussion, add Inspector_Name field and drop Inspector ID.  Should be populated on insert and never change.

**Comment by kanglu666** [comment]
done at KCI version, please test

**Comment by JMurk** [comment]
Confirmed complete @ KCI
