### ISSUE TITLE
FSE Application - Existing Delete Functions

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#15]
Issue:  When a user clicks on any of the delete functions, there is no warning message.

Resolution:  Please add a warning/confirmation message upon user click of delete.  It should read: "Are you sure you want to delete the current inspection?" Or whatever it was deleting.  It should provide options of OK and Cancel.

**Comment by kanglu666** [comment]
test at KCi version
http://dashboard.kci.com/fogservicesnew/index.html

**Comment by JMurk** [comment]
I'm not seeing the Delete buttons....

![image](https://f.cloud.github.com/assets/5805454/2050753/e0a76f18-8a7b-11e3-9cb8-ddf840643ad7.png)

**Comment by JMurk** [comment]
Scratch that... Delete buttons found on iPad.  Confirmed complete @ KCI
