### ISSUE TITLE
FSE Application - GCD Details - Air Vent Field

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#16]
Issue:  The Air Vent field on the GCD Details page should be a dropdown with values of Yes, No, and Unknown.  

Resolution:  Remove the toggle button and replace with dropdown list.  This may require a DB schema change.

**Comment by kanglu666** [comment]
yes, need DB schema change. let's talk about this.

**Comment by JMurk** [comment]
Per discussion, please add a 2 as a valid value and change the UI from a toggle to a dropdown with values of "Yes", "No", and "Unknown"

**Comment by kanglu666** [comment]
done at KCI , please test

**Comment by JMurk** [comment]
Confirmed complete @ KCI
