### ISSUE TITLE
FSE Application - Delete FSEs

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#17]
Issue:  PC users would like the ability to delete FSE records.  

Resolution:  Add a Delete function (similar in design to the existing ones) that adheres to the following rules:

-The user MUST be an admin (we will need to use the FSE_USER table for security).  Other wise the delete button should be hidden.
-The FSE may not be deleted if there are existing inspection/details associated to it.  If the user attempts to delete a record with dependencies, it should prompt an error message.
-Must have a warning/confirmation window.

**Comment by kanglu666** [comment]
FSE cant be delete is the original requirement. 
but yes, we can apply this function. this will need some effort.
need a list of user names who are admin and have the delete FSE right.
let's talk about this function.

**Comment by JMurk** [comment]
Per discussion, we will add security to make this function available to admins ONLY.  A request has been sent to the stakeholders for a list of these users.

**Comment by JMurk** [comment]
Confirmed complete @ KCI
