### ISSUE TITLE
FSE Application - Edit FSE ID (PCID)

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#18]
Issue:  PC would like the ability to edit the PC ID (displayed in the app as FSE ID).  

Resolution:  Please make this an editable field for ADMINS ONLY.

**Comment by kanglu666** [comment]
PC ID is FSE NUMBER in the app.

**Comment by JMurk** [comment]
Yes, that field should be editable for ADMINS ONLY.  Confirmed can edit.

**Comment by JMurk** [comment]
Confirmed complete @ KCI
