### ISSUE TITLE
FSE Application - GCD Inspection Details - Last Updated Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#19]
Issue:  GCD Inspections do not store the last updated user or last updated date.

Resolution:  Please add these fields for this table and page.

**Comment by kanglu666** [comment]
DB schema change, let's talk about this.

**Comment by JMurk** [comment]
Per discussion, add these fields for BOTH GCD Inspection and FSE Inspection.  Also, create two new tables for GCD inspection history and FSE inspection history.  These tables will log each insert/update performed.

**Comment by kanglu666** [comment]
done at KCI

**Comment by JMurk** [comment]
Last Update date does not appear to be auto-populating for either table.

**Comment by kanglu666** [comment]
working.

**Comment by JMurk** [comment]
Confirmed complete @ KCI
