### ISSUE TITLE
FSE Application - Settings - Add Symbology

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#20]
Issue:  PC would like to have a legend for the feature on the map.

Resolution:  Within the settings tab, add the symbol next to the layer (for FSEs at a minimum).

![image](https://f.cloud.github.com/assets/5805454/2010988/a0f08ec2-8774-11e3-86f9-f4072e9f5088.png)

**Comment by kanglu666** [comment]
test at KCi version
http://dashboard.kci.com/fogservicesnew/index.html

**Comment by JMurk** [comment]
Confirmed complete @ KCI
