### ISSUE TITLE
FSE Application - Query for Inspections by Date Range

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#21]
PC would like the ability to query for the number of inspection performed within a given date range.  The user must be able to input begin and end dates and the system should produce a report/page with the total number a list of the inspections with basic info.

Brendan-  What is the best way to handle this?

**Comment by JMurk** [comment]
Please provide input.

**Comment by BC89** [comment]
Eric we need a LOE to complete this task. We'll use SQLReporting and develop the signature necessary to support fro/to date ranges

**Comment by tarheelgis** [comment]
Sweet

iSent this from my iPhone

On Feb 24, 2014, at 11:23 AM, "Brendan" <notifications@github.com<mailto:notifications@github.com>> wrote:

Eric we need a LOE to complete this task. We'll use SQLReporting and develop the signature necessary to support fro/to date ranges

**Comment by tarheelgis** [comment]
Added this functionality URL parameters are StartDate and EndDate. Please test once code is posted

**Comment by JMurk** [comment]
Completed and implemented @ CIty
