### ISSUE TITLE
FSE Application - Export list of NOVs

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#22]
PC would like the ability to export a list of all NOVs to an Excel spreadsheet.  Formatting was not a major concern.

Brendan, can you determine the best approach and assign accordingly?

**Comment by JMurk** [comment]
Please provide input.

**Comment by BC89** [comment]
Eric we need LOE to complete this task. I would like a simple SQLReport following the same established pattern.

**Comment by tarheelgis** [comment]
Added page to app NOV.aspx that contains report sorted by action date. Clicking export to excel will provide export result. Please preview and provide feedback once code is posted to test.

**Comment by JMurk** [comment]
Completed and implemented @ CIty
