### ISSUE TITLE
FSE Application - GCD Details -FSE Number Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#24]
Issue:  The FSE Number label is in all caps.  

![image](https://f.cloud.github.com/assets/5805454/2011300/06ac6eb2-8779-11e3-823b-12f20e0c5469.png)

Resolution:  Please update the label to read "FSE Number"

**Comment by kanglu666** [comment]
test at KCi version
http://dashboard.kci.com/fogservicesnew/index.html

**Comment by JMurk** [comment]
This is still and issue on the following pages:
-FSE Inspection Details page
-GCD Inspection Details page
-Add New Enforcement Action page

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Found others:  

-Enforcement Action Details
-Add New FSE Inspection
-Add New GCD Inspection

**Comment by JMurk** [comment]
Confirmed complete @ KCI
