### ISSUE TITLE
FSE Application - Photos - Attach Photos Button

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#26]
Issue:  Since the Photos page will be used for attaching photos and viewing existing photos, I think the button should be more general, like "FSE Inspection Photos"

Question:  Wasn't there Delete buttons where the Photos buttons are now?

Resolution:  Please change the name of the button.

**Comment by kanglu666** [comment]
there is no Delete Photos Function, just Add photos function now.
but if it's needed or required, we can figure out a solution;
i will change the button name

**Comment by JMurk** [comment]
Per discussion, add "Remove" function that will delete the photo DB record, but not the physical photo file.

**Comment by JMurk** [comment]
Confirmed complete @ KCI
