### ISSUE TITLE
FSE Application - Pending Edits Notification

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#27]
Issue:  Whenever there are pending edits and a user tries to navigate away from the page, a warning message is not prompted.

Steps to Recreate:
1. Open an FSE
2. Make a few edits and do not click save
3. Click back

Resolution:  Please add a warning message of "The are unsaved edits, navigating away from this page will lose all changes." and provide options of "Continue" and "Cancel"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Needs to be implemented separately for each page rather than at the FSE Details level.  Changes are lost prior to the edits message being received.  Please implement for the following pages:

FSE Details
FSE Inspection
GCD Inspection
GCD Details
Enforcement Action Details

**Comment by kanglu666** [comment]
done at city, clear your cache thest

**Comment by JMurk** [comment]
confirmed complete @ City
