### ISSUE TITLE
FSE Application - FSE Details - Always Editable

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#28]
Issue:  It appears that FSE detail for existing FSE is always editable.  It should only become editable once the user clicks the "edit" button.

Resolution:  Please disable editing on the FSE Details page until the edit button is clicked.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
It appears that this is an issue with every page.  Please update all pages with edit functionality.

Also, the user should be able to tell that a page goes from non-editable to editable.  When fields are non-editable, the should be tinted grey (I think FSE details was like this at one point).  Once the user selects Edit, the fields will become white.  Please update for all pages with edit functionality.

**Comment by JMurk** [comment]
Confirmed complete.
