### ISSUE TITLE
FSE Application - Add NOV Button

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#29]
Issue:  Change the "Add Notice of Violation" button to read "Add Enforcement Action"

![image](https://f.cloud.github.com/assets/5805454/2050811/d69ebb2e-8a7c-11e3-88f3-82ef8d4aeb02.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete @ KCI
