### ISSUE TITLE
FSE Application - FSE Details - Update Confirmation Window

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#3]
Issue:  On the successful update confirmation window, the message reads "Data Updated successfully."  The S in successfully should be capitalized.

![image](https://f.cloud.github.com/assets/5805454/2009158/c82a851c-8759-11e3-8bbf-0493bde97a65.png)

Resolution:  Please update the message so that it reads: "Data Updated Successfully"

**Comment by kanglu666** [comment]
test at KCi version
http://dashboard.kci.com/fogservicesnew/index.html

**Comment by JMurk** [comment]
Confirmed complete @ KCI
