### ISSUE TITLE
FSE Application - NOV - Add New Enforcement Action

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#31]
Issue:  When adding a new enforcement action to an FSE that already has an Enforcement action related to it, the system pre-populates the Add New form with the existing Enforcement Action's attributes.

Steps to recreate:
1. Open an FSE
2. Click NOV
3. Click Add New
4. Create a New Enforcement Action
5. Return to the NOV List
6. Click Add New

Resolution:  Please investigate and resolve so that the Add new form is always blank.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete @ KCI.
