### ISSUE TITLE
FSE Application - NOV Deatils - Change Header

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#32]
Issue:  The header for the Details page reads "FSE NOV Details."

![image](https://f.cloud.github.com/assets/5805454/2051042/f5157f5c-8a81-11e3-837f-6305a6a49ae1.png)

Resolution:  Please update the header to read "Enforcement Action Details"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Need to add an s to the end of "Detail" so that it reads "Details"

**Comment by JMurk** [comment]
Confirmed complete @ KCI
