### ISSUE TITLE
FSE Application - Photos - Description Input box Misaligned  

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#34]
Issue:  The Description label box and input box are a bit misaligned along the bottom line.

![image](https://f.cloud.github.com/assets/5805454/2051218/668f2b1c-8a85-11e3-9ea9-62c822d08f7e.png)

Resolution: Please align the boxes.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete @ KCI.
