### ISSUE TITLE
FSE Application - Photos - Upload Message

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#36]
Issue:  When only one photo file is uploaded, the message reads "1 Files Loaded!"  

![image](https://f.cloud.github.com/assets/5805454/2051575/2d34b598-8a8b-11e3-81b6-4333892dcba5.png)

Resolution:  Please remove the s from "Files"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete @ KCI
