### ISSUE TITLE
FSE Application - 25% Rule Calculation Error

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#37]
Issue:  There are a few issues with the 25% rule calculation:
1. The calculation is not consistently outputting the correct value.  
2. The system is rounding up too much.  

Resolution:  Please investigate the equation being used.  It should be (Grease Cap + Sediment)/(GCD Hydraulic Depth).  Make sure that the percentage always has 2 decimal places.

**Comment by kanglu666** [comment]
fixed on both KCi and City

**Comment by JMurk** [comment]
Appears to be fixed.
