### ISSUE TITLE
FSE Application - Add New Inspection Headers

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#38]
Issue:  On both the Add new GCD inspection and Add new FSE inspection pages, the word "inspection" is not capitalized.

Resolution:  Please update so that the headers read:

"Add New FSE Inspection"
"Add New GCD Inspection"

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete @ KCI
