### ISSUE TITLE
FSE Application - New FSE - Duplicate FSE Numbers (PCID)

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#4]
Issue:  The system is generating duplicate FSE Numbers (PCIDs) when two users create FSEs at the same time.  Specifically the occurs when User A adds a new FSE and then User B creates a new FSE before User A has clicked save.

Resolution:  When the web service returns the next highest PCID, the system should save the record to the database.  There are two ways to do this:
1. Save the record immediately when a user clicks New FSE (not recommended).
2. Wait to retrieve the ID until the user clicks save and commits the record to the database (recommended).

**Comment by kanglu666** [comment]
as i remember, Amy told me that the PCIDs can be duplicate and even null. that y we use FSE ID as the primary KEY for all the relationships with other table. if that's the case, we can leave it as is.
if not, we can figure out a solution.

**Comment by JMurk** [comment]
Per discussion, leave as is.
