### ISSUE TITLE
FSE Application - Report - Solids Int.? 

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#40]
Issue:  The report is printing Yes/No values for Solids Int. (GCD Details) in all lower case.  The application inputs proper case values.

Resolution:  Please apply proper case for the field.  If it is a data issue only, please pass back to me and I will update existing data.

**Comment by tarheelgis** [comment]
In the GCD_DETAILS table on KCI-TSSQL03\SDE the values are Yes, No, N/A and blank with no full upper case conversion applied within my report sql currently. The report returns the data as it is entered through the app. I can return all values as upper case by adjusting my SQL for the report or if the entry is supposed to be upper than we could classify this as a data issue. Let me know.

**Comment by JMurk** [comment]
I went ahead and updated all records to be "Yes" and "No" (proper case), so as long as the report pulls the actual value, it should be resolved.
