### ISSUE TITLE
FSE Application - Data Successfully Updated Modal

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#41]
Issue:  After saving a few inspections, the "Data Successfully Updated" modal screen gets stuck.  Pressing OK will not close the window.  Users are forced to log out and log back in to get it to go away.

Resolution:  Please investigate and resolve accordingly.

**Comment by JMurk** [comment]
Any insight into this issue?

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed Complete.
