### ISSUE TITLE
FSE Application - NOV Report - Add Data to Output

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#42]
Please add the additional fields noted in the spreadsheet provided by Pollution Control.

**See email for attachment and details

**Comment by JMurk** [comment]
Linking FSE inspection to NOV.  Will be able to get Inspection date from there.

**Comment by tarheelgis** [comment]
Has this link been completed yet? and if so which fields is the linkage applied to

**Comment by JMurk** [comment]
Look into the following gaps:
1.  GCD Location. Same issue as above with multiple GCD locations
2.  Comments1. This field does not exist in either table
3.  FSE Number Assigned by App. Also not sure where to dig this up
4.  Needs WWDP. This field does not exist in either table
5.  Sent to HCD Date. This field does not exist in either table
6.  Sent to Health Dept Date.  This field does not exist in either table

**Comment by JMurk** [comment]
Schema Changes (FSE_COMPLIANCE) for Joe:
- Change Action Date to Inspection Date (autopopulate w/ most recent fse inspection date)
- Add Comments (see list of valid options - Lu to code)
- Add Permit Expired (Y/N toggle, autoset with WWDP Exp Date)
- Add Needs WWDP (Y/N toggle, autoset with 9**\* FSEs)
- GCD Location (talk to developers on how to pick)

**Comment by JMurk** [comment]
Complete at KCI and City.  Lu, please make adjustments in the app.  Please take note of the details of how to populate some of the fields above.

**Comment by kanglu666** [comment]
FSE app has been updated at city, please test

**Comment by JMurk** [comment]
Eric, please add to the report.

**Comment by JMurk** [comment]
A couple things:

-FSE ID should display PC ID from the database (that is how the know FSE ID).
-Missing GCD Location

**Comment by tarheelgis** [comment]
PC ID is not in the NOV table which table should I get PC ID from?

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
