### ISSUE TITLE
FSE Application - FSE Detail Report - Solid Int.?

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#44]
Issue:  The report is still printing the contents of the Solids Int.? field in all lowercase.

![image](https://cloud.githubusercontent.com/assets/5805454/2782027/e534ded2-cb1a-11e3-890a-63a675eda1cc.png)

Resolution:  Please investigate and update so that values are printed in proper case.

**Comment by tarheelgis** [comment]
completed please check when changes post

**Comment by JMurk** [comment]
Confirmed complete.
