### ISSUE TITLE
FSE Application - FSE Detail Report - Sediment Units

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#46]
Please add (in) to the end of the SEDIMENT label within the GCD Inspection Details page.

![image](https://cloud.githubusercontent.com/assets/5805454/2782145/4298fe2c-cb1c-11e3-96d3-de608738a902.png)

**Comment by tarheelgis** [comment]
completed please check when changes post

**Comment by JMurk** [comment]
Where do we stand with posting these changes???

**Comment by tarheelgis** [comment]
Completed check again

**Comment by JMurk** [comment]
confirmed complete.
