### ISSUE TITLE
FSE Application - Display GCD Location on GCD Inspection

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#49]
Please display the GCD Location field (stored in GCD Details) in the related GCD Inspections.

![image](https://cloud.githubusercontent.com/assets/5805454/2782337/585009f2-cb1e-11e3-8e9f-3e33469c2ad7.png)

If possible, display between the GCD ID and GCD Inspection ID fields, as shown in the image above.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
