### ISSUE TITLE
FSE Application - Add Fields to GCD Inspection

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#50]
Please add the following fields to GCD Inspection in the database and the application:

<ul>
<li>What Sinks Discharge to GCD? (DISCHARGE_SINKS, varchar(255) </li>
<li> Anything Else Going to GCD? (GCD_RECEIVING, varchar(255)</li>
<li> Deep Fryers (FRYERS, int yes/no)</li>
<li> Wok Station (WOK, int yes/no)</li>
</ul>

**Comment by tarheelgis** [comment]
Will integrate in report when these make it into table

**Comment by JMurk** [comment]
Joe to make schema changes.

**Comment by JMurk** [comment]
Schema has been updated.

**Comment by JMurk** [comment]
Lu, please add these fields to the application above Last Updated By.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Lu, can you make the following changes to the labels:

-"Which Sinks Discharge to GCD?"
-"Deep Fryers?"
-"Wok Station?"

**Comment by kanglu666** [comment]
done,clear browser cache

**Comment by JMurk** [comment]
Confirmed complete.
