### ISSUE TITLE
FSE Application - GCD Inspection - Cleaning Frequency

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#51]
Please make the following updates:

<ol>
<li>Covert existing data to Days (Joe)</li>
<li>Add "(Days)" to the field label on the app screen</li>
<li>Force the user to only enter numbers</li>
<li>Provide a message to the user when a non-numerical value is entered</li>
</ol>

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
