### ISSUE TITLE
FSE Application - Link FSE Compliance to FSE_INSPECTION

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#52]
1. Please add FSE_INSPECTION_ID to the FSE_COMPLIANCE table as a FK. 
2. Please move NOV button to the FSE Inspection Page.
3. Add Inspection Date to the NOV report (Eric)

**Comment by JMurk** [comment]
Lu, has this schema change been made?

**Comment by tarheelgis** [comment]
Inspection Date is waiting on feedback from stakeholders

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
DB updates made, Eric- please update the report

**Comment by JMurk** [comment]
Complete.
