### ISSUE TITLE
FSE Application - Update Font Color

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#53]
Please change the font color for "Continue will lose all changes" to white.  Make sure the change is made everywhere this message persists.

![image](https://cloud.githubusercontent.com/assets/5805454/3066975/4141ab1e-e27d-11e3-8298-f22467a20972.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
