### ISSUE TITLE
FSE Application - Enforcement Action - Permit Expired

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#54]
Issue:  The "Permit Expired" field label has incorrect capitalization.

![image](https://cloud.githubusercontent.com/assets/5805454/3314146/925bd766-f6ed-11e3-978e-9a1be6d6b7dd.png)

Resolution:  Please set to "Permit Expired?"

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
