### ISSUE TITLE
FSE Application - Enforcement Action - Comments Dropdown

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#57]
For the Comments field in Enforcement Actions, add a dropdown list for users to choose from.  Here are the values that should be included in the dropdown:

Failed 25% rule 
No GCD
No WWDP
Expired WWDP
Enzymes used directly in GCD
GCD leaking
Dishwasher connected to GCD
Inaccessible GCD
GCD not connected
No/Missing baffles
Baffles not installed correctly
GCD installed backwards
Pre-Rinse sink not connected to GCD
Refused admittance
Other

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Confirmed complete.
