### ISSUE TITLE
FSE Application - Tab Label

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#6]
Issue: The tab label is "fog."  It should read "FOG."

![image](https://f.cloud.github.com/assets/5805454/2009282/d7c132a8-875b-11e3-8df6-8645dce77586.png)

Resolution:  Please update to "FOG"

**Comment by kanglu666** [comment]
test at KCi version
http://dashboard.kci.com/fogservicesnew/index.html

**Comment by JMurk** [comment]
Confirmed complete @ KCI
