### ISSUE TITLE
FSE Application - Black-on-Brown Text

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#60]
Issue:  Please update ALL modal screens so that the text on top of brown backgrounds is white, not black.

![image](https://cloud.githubusercontent.com/assets/5805454/3315036/e93ee146-f6f6-11e3-9023-42a77b87d277.png)

**Comment by kanglu666** [comment]
updated

**Comment by JMurk** [comment]
Lu--- Please check ALL modal screens.  I still see some that have this text combination.

**Comment by kanglu666** [comment]
done, please test at dev: 
http://dpw-gw03dev-srv/water/fogservicesnew/index.aspx

**Comment by JMurk** [comment]
Should be complete.  Will reopen if any more are discovered.

**Comment by JMurk** [comment]
Push to prod.

**Comment by kanglu666** [comment]
prod updated

**Comment by JMurk** [comment]
Confirmed complete.
