### ISSUE TITLE
FSE Application - Map Identify Not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#61]
Issue:  Every time I try to identify an FSE point on the map, I receive the following error:

![image](https://cloud.githubusercontent.com/assets/5805454/3315068/399356fe-f6f7-11e3-8652-c09985260f1d.png)

Resolution:  Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete
