### ISSUE TITLE
FSE Application - NOV Report - Remove FSE Inspection ID

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#65]
Please remove the FSE INSP. ID column from the report.  The stakholders say they do not need to see it.
![image](https://cloud.githubusercontent.com/assets/5805454/3755106/bc94cf7e-1821-11e4-92a3-fc2f9ab9ae1c.png)

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
