### ISSUE TITLE
FSE Application - Grills, Woks, Deep Fryers - Counts

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#67]
Please add a field called Grills (int) to GCD Inspections.  In the app, it should be placed above Deep Fryers.

Also, Deep Fryers and Wok Station should be changed to an integer field.  The "?" should also be removed from both labels.  Default value for all 3 fields will be 0.

**Comment by kanglu666** [comment]
FES db schema updated on dev. 
FSE app has been updated at dev, please test.
http://dpw-gw03dev-srv/water/fogservicesnew/index.aspx

**Comment by JMurk** [comment]
These should be integer fields that allow users to enter a number.  They should not be toggles.

**Comment by kanglu666** [comment]
updated for both dev and prod.

**Comment by JMurk** [comment]
Confirmed complete on prod, still need to change from toggles on dev.

**Comment by kanglu666** [comment]
it is updated on dev. please clear browser cache and test

**Comment by JMurk** [comment]
Confirmed complete.
