### ISSUE TITLE
FSE Application - GCD Details - Default Value

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#68]
Please set the default value for Shape in GCD Details to "Rectangle"

![image](https://cloud.githubusercontent.com/assets/5805454/3755630/d6bf0da6-1826-11e4-853c-907983d9e28c.png)

**Comment by kanglu666** [comment]
done, please test at dev: 
http://dpw-gw03dev-srv/water/fogservicesnew/index.aspx

**Comment by JMurk** [comment]
Confirmed complete in dev.  Please push to prod.

**Comment by kanglu666** [comment]
updated for both dev and prod

**Comment by JMurk** [comment]
Confirmed complete.
