### ISSUE TITLE
FSE Application - Cannot Delete FSE Inspections

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#69]
**Issue:**  When trying to delete an existing FSE Inspection, nothing happens.  This is an issue on BOTH DEV and PROD

**Resolution:** Please investigate and resolve accordingly.

Use FSE # 404651
The Playbook Bar
6700 German Gill Rd, 

Inspection IDs 2572,2573 & 2574 all need to be deleted.

**Comment by kanglu666** [comment]
fixed, please test

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by kanglu666** [comment]
done on PROD, please test

**Comment by JMurk** [comment]
Confirmed complete.
