### ISSUE TITLE
FSE Application - FSE Report - Yes/No For All Binary Fields

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#7]
Issue:  In the report, all binary fields are displayed as 0 or 1.  These fields should display Yes or No.

![image](https://f.cloud.github.com/assets/5805454/2009377/5e48b6b0-875d-11e3-9bed-9f7cb27969fe.png)

**Amy mentioned that this had been resolved previously, however the current version of the report at the city says otherwise.  Perhaps the latest version isn't being accessed by the app?

Resolution:  Please update so that all binary fields display their yes/no labels.

**Comment by JMurk** [comment]
Lu, please publish/link the latest version of the report to the application.

**Comment by kanglu666** [comment]
http://dpwview.baltimorecity.gov/fsereport/fogmain.aspx?fseid=5984

**Comment by JMurk** [comment]
Confirmed Complete.
