### ISSUE TITLE
FSE Application - NOV Comments - Add Vaules

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#70]
Please add the following values to the NOV Comments pick-list:

NO MAINTENANCE LOG
INLET AND/OR OUTLET TEE MISSING
FAILED 25 % RULE 2ND NOTICE
FAILED 25% RULE 3RD NOTICE
WOK STATION NOT CONNECTED TO GCD

**Comment by kanglu666** [comment]
done at city dev, please test

**Comment by JMurk** [comment]
Can you please make these proper case?

No maintenance log
Inlet and/or outlet tee missing
Failed 25% rule - 2nd notice
Failed 25% rule - 3rd notice
Wok station not connected to GCD

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete in both dev and prod.
