### ISSUE TITLE
FSE Application - NOV Report - Rearrange Report and Add Blank Coulmns

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#71]
In order to have downloadable spreadsheet into the format we use for mail merge activities, the following fields need to be in this exact order with a blank field where indicated.  Otherwise, we will have to rearrange it after the download:
1.  Inspection date
2.  FSE ID
3.  Blank field
4.  Facility name
5.  Blank field
6.  Blank field
7.  Blank field
8.  Facility Address
9.  City
10. State
11. Zip code
12. Comments
13. Violation type
14. Needs WWDP
15. Enforcement Action
16.  NOV sent
17. NOV Date
18. Date received by FSE
19. Response due date
20. FSE response date
21. Status
22. Compliance comments
23. Permit expired (note:  this is displaying as O or 1 would prefer yes or no)

Please make the blank columns very narrow.

**Comment by kanglu666** [comment]
updated in city dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, please push to prod.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
