### ISSUE TITLE
FSE Application - Map Button Not Working

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#72]
**Issue:**  On the FSE Search page, the Map button never becomes active.

![image](https://cloud.githubusercontent.com/assets/5805454/4737074/1143b6d6-59f2-11e4-8da9-1ff60ee52a1b.png)

**Resolution:** Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed in dev, please test

**Comment by JMurk** [comment]
Confirmed complete in dev, push to prod.

**Comment by kanglu666** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
