### ISSUE TITLE
FSE Application - GCD Inspection - Grills Value Not Saving

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#73]
**Issue:**  When editing or adding a new GCD inspection, values put into the Grills field saves initially, but then does not appear on the screen when you close it then open it back up.

![image](https://cloud.githubusercontent.com/assets/5805454/4812056/5f44c50c-5ebe-11e4-9d23-f0361a9f16b5.png)

**Steps to Recreate:**  
1. Open an existing GCD Inspection
2. Edit the Grills field
3. Tap save
4. Tap back to return to the list.
5. Open the same Inspection from the list

**Resolution:** Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
fixed, please test

**Comment by JMurk** [comment]
Confirmed complete.
