### ISSUE TITLE
FSE Application - NOV - Date Controls

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#74]
Is it possible to take the calendar control off of the date fields on the Enforcement Action screen?  The users would like to type in the date manually.

If so, please remove the control from all date fields on the Enforcement Action screen.

**Comment by jday3** [comment]
I can make this a text field, but does there need to be validation of the format?

**Comment by JMurk** [comment]
It should be a date picker, like the FSE Inspection Summary Start and End Dates

**Comment by jday3** [comment]
I guess I'm confused. Both of the date fields have the same date picker. 

![enforcement](https://cloud.githubusercontent.com/assets/4439618/5384743/08b19236-808a-11e4-91e5-8c7a3cdc73fe.PNG)

![reports](https://cloud.githubusercontent.com/assets/4439618/5384744/08b64826-808a-11e4-9fd4-42a2603903c2.PNG)

**Comment by JMurk** [comment]
Please try to keep the fields DATE data types, but have a manual input with validation of the format yyyy-mm-dd.

**Comment by jday3** [comment]
Done, on dev.

**Comment by JMurk** [comment]
Looks good, please push to prod.

**Comment by jday3** [comment]
Now on prod

**Comment by JMurk** [comment]
Confirmed complete.
