### ISSUE TITLE
FSE Application - NOV - Move Comments field

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#75]
Please move the Comments field on the Enforcement Action screen after Inspection Date and Before Violation Type.

![image](https://cloud.githubusercontent.com/assets/5805454/5071202/d1061a50-6e3c-11e4-911a-ace4bfd142e4.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, push to prod.

**Comment by jday3** [comment]
On prod

**Comment by JMurk** [comment]
Confirmed complete.
