### ISSUE TITLE
FSE Application - NOV Report - Add Date Filters

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#76]
Please add Start Date and End Date filters to the NOV report list.

![image](https://cloud.githubusercontent.com/assets/5805454/5071225/fc58c392-6e3c-11e4-9f7f-edd2327380fe.png)

![image](https://cloud.githubusercontent.com/assets/5805454/5071222/f7fb37e4-6e3c-11e4-9e60-f862ac4a4a52.png)

**Comment by jday3** [comment]
Which date field should the query be based on? Many of the records don't have an Inspection Date or a NOV Date

**Comment by JMurk** [comment]
Lets go with NOV date.  In production they are populated more consistently.  Also, if they do not enter dates, the report should return all records.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, push to prod.

**Comment by jday3** [comment]
On prod

**Comment by JMurk** [comment]
Confirmed complete.

**Comment by JMurk** [comment]
Please change the date filter to use Inspection date rather than NOV date.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Comfirmed complete.
