### ISSUE TITLE
FSE Application - NOV - Violation Type will not save

### ISSUE THREAD

**Issue by DaveThomKCI** [JMurk/FSE_Application_Issues#77]
I tried for two different inspections to create a violation, and make the type "Inadequate maintenance of waste/recycle grease area" and it will not save.

**Comment by JMurk** [comment]
Good catch.... field length of VIOLATION_TYPE was 50, that has 51.  I updated it to 60.  Lu to update web service.

**Comment by kanglu666** [comment]
updated.

**Comment by JMurk** [comment]
Dave, please confirm and close.

**Comment by DaveThomKCI** [comment]
Tested.  Confirmed fixed.
