### ISSUE TITLE
FSE Application - Deleting Dates

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#78]
**Issue:**  The users would like to be able to delete dates from all date fields within the application. 

**Resolution:**  Please add functionality to allow them to delete dates or set the date to be blank.

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Looks like you are able to delete on the NOV page, but nowhere else.  Can we expand this functionality to all other editable dates?

**Comment by jday3** [comment]
Done, on dev. Button to clear is on date picker toolbar

**Comment by JMurk** [comment]
Awesome.  Confirmed complete, please push to prod.

**Comment by jday3** [comment]
Now on prod

**Comment by JMurk** [comment]
Confirmed complete.
