### ISSUE TITLE
FSE Application - FSE Report - Date/Time Fields - Display Date Only

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#8]
Issue;  The report displays date/time fields when only date is captured in the application, leaving time to default to 12:00:00AM.  Only date should be displayed.

![image](https://f.cloud.github.com/assets/5805454/2009407/d2f2d9f0-875d-11e3-93a3-a4fd7a2f9c61.png)

Resolution: Please remove time from the display.

**Comment by JMurk** [comment]
Confirmed complete @ City

**Comment by JMurk** [comment]
Still an issue for Last Updated dates (FSE Inspection & GCD Inspection)

**Comment by tarheelgis** [comment]
Could this be an issue with deployment? I have tested this a few ways on my end and it seems to be fine.
![2014-02-27_11-49-06](https://f.cloud.github.com/assets/6514808/2284980/72c23064-9fcf-11e3-9f51-de74c350fd26.jpg)

**Comment by JMurk** [comment]
The field you show above is correctly only displaying date, however the LAST_UPDATED dates are not:

![image](https://f.cloud.github.com/assets/5805454/2294138/8fa0bd2e-a07c-11e3-9eed-1b3b752e357a.png)

FSE INSPECTION DETAILS and GCD INSPECTION DETAILS both have this problem.

**Comment by tarheelgis** [comment]
Updated please test when code is posted.

**Comment by JMurk** [comment]
Confirmed completed @ City
