### ISSUE TITLE
FSE Application - Enforcement Action Page - Dropdowns are Holding Values from Previous

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#80]
**Issue:** - Within the Enforcement Action page, the dropdowns seem to hold the selected value from the previously opened record without anythng actually being selected.  In the screenshot below, you will notice that "unauthorized discharge" is selected in the dropdown, but is not actually in the field.

This seems to occur with all dropdowns on this page.

![image](https://cloud.githubusercontent.com/assets/5805454/6254511/38196bf6-b777-11e4-9426-cc12f29a0cea.png)

**Resolution:** Please update so that when the field is blank, on the form, nothing is checked in the dropdown.

**Comment by jday3** [comment]
Fixed on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
