### ISSUE TITLE
FSE Application - Enforcement Action - Add Dropdown for Status

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#81]
Please add a dropdown for the status field within the enforcement action page.  Valid Values will be:

-Open
-Closed

![image](https://cloud.githubusercontent.com/assets/5805454/6254573/e032f2bc-b777-11e4-90c4-15b43c2be762.png)

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
