### ISSUE TITLE
FSE Application - FSE Details - New SIC Codes

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#83]
Please add 5431 and 8661 to the SIC Code dropdowns (SIC1, SIC2, SIC3)

![image](https://cloud.githubusercontent.com/assets/5805454/6446926/7d342398-c0dc-11e4-93b8-802c24122b94.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
