### ISSUE TITLE
FSE Application - Enforcement Action - Comments in Different Location

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#84]
Per stakeholder:  Violation Type & Comment are next to each other, but if go back after saving it,  Comment moves to the bottom, Anyway we can keep Comment next to violations when we are only viewing and/or editing this page?

![image](https://cloud.githubusercontent.com/assets/5805454/6671549/597e6c6e-cbdc-11e4-8b56-4399a84e7206.png)

**Comment by jday3** [comment]
Done on dev/prod

**Comment by JMurk** [comment]
Confirmed complete in both environments.
