### ISSUE TITLE
FSE Application - FSE Details - Add ACTIVE? Value

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#86]
Please add a value of "ACTIVE/LATE OPENING" to the Active? dropdown list on the FSE Details page.

![image](https://cloud.githubusercontent.com/assets/5805454/7454752/c15f1552-f244-11e4-939b-c3bc5b03e513.png)

**Comment by jday3** [comment]
Done, on dev

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Closing.
