### ISSUE TITLE
FSE Application - Forms Won't Load

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#87]
**Issue:** Users are reporting that forms will not load when trying to access pages (e.g. FSE Details) in the FSE Application.

![fse_bug](https://cloud.githubusercontent.com/assets/5805454/7814873/05444224-0393-11e5-810f-833a88db0cff.png)

**Comment by jday3** [comment]
fixed

**Comment by JMurk** [comment]
Confirmed complete.
