### ISSUE TITLE
FSE Application - FSE Inspection - Data Type Updates

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#88]
We need to change the data types for the INSPECTION_DATE and the LAST_UPDATED_DATE from "date" to "datetime" so that the fields are viewable in ArcMap.

Please make sure that all forms work as well as the reports.  

The data type changes have been made in dev.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
For Inspection Date, only have the date selectable in the UI, not the time.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete on dev, will coordinate production move off-hours.

**Comment by jday3** [comment]
This is complete on production

**Comment by JMurk** [comment]
Confirmed complete.
