### ISSUE TITLE
FSE Application - FSE Report - Labels to Include Units of Measure

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#9]
Issue:  Report labels do not include units of measure.

![image](https://f.cloud.github.com/assets/5805454/2009507/36e1f7ba-875f-11e3-82fa-63f65e3eca7d.png)

Resolution: Please add the units of measure to the end of the labels in parenthesis.  Example: Depth (ft)  

-Length
-Depth
-Width/Diameter
-Hydraulic Cap.
-Rated Cap.
-In Pipe Depth
-Out Pipe Depth

**Comment by JMurk** [comment]
Please change Hydraulic Cap and Depth to Inches.

**Comment by tarheelgis** [comment]
Should Rated Cap also be inches?

**Comment by JMurk** [comment]
They marked up a report with these changes and rated cap was left alone.  So for now, leave it as is.

**Comment by tarheelgis** [comment]
Updated please test when code is posted

**Comment by JMurk** [comment]
Confirmed completed @ City
