### ISSUE TITLE
FSE - Add Comments to FSE Deatils

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#90]
The users are requesting that a comments field be added to the FSE Details page.  On the UI, this should be placed between the Contact Email field and the Last Update Date field.  

![image](https://cloud.githubusercontent.com/assets/5805454/10226826/bf9b2346-6837-11e5-95dc-77b9612ef844.png)

I have added the field to the FSE_LOCATION table in dev.

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Confirmed complete.  Please push to prod.  Comments field has been added to the production DB.

**Comment by jday3** [comment]
done on prod

**Comment by JMurk** [comment]
Confirmed complete.  Also fixed reported issue with datatype.
