### ISSUE TITLE
FSE - Delete GCD Function

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#92]
Admins are requesting that a delete button/function be added to the GCD Details page.  This should:

-Be restricted to only admins
-Check to see if there are related GCD inspections.  When they exist and the user clicks delete, the system should prompt a message stating "Inspections exist for this GCD, unable to delete"
- Prompt a confirmation form - "Are you sure you want to delete this GCD?"

**Comment by taojun545** [comment]
Added Delete GCD Function on dev.

**Comment by JMurk** [comment]
Please change the warning message to read "The selected GCD has related inspection records and cannot be deleted!"

![image](https://cloud.githubusercontent.com/assets/5805454/13610807/76ae9d34-e52d-11e5-8142-37aeee3e82bc.png)

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
