### ISSUE TITLE
FSE - New Report - FSE List

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#94]
**Description:**  Users have requested a new report to be added to the FSE Reports page.

![image](https://cloud.githubusercontent.com/assets/5805454/13606398/d3b0e56e-e519-11e5-8c6a-e79885c989d6.png)

This report will be called _FSE List_ and will include a parameter for Zip Code in which users can pick none (returns all), one, or many.  The fields returned should be as follows:
- FSE_LOCATION. PC_ID
- FSE_LOCATION.FACILITY_NAME 
- FSE_LOCATION.FSE_ADDRESS
- FSE_LOCATION.ZIP_CODE
- FSE_INSPECTION.\*  (from the most recent inspection)

For this, you will need to join FSE_LOCATION to FSE_INSPECTION using the most recent records in the FSE_INSPECTION table for each FSE_LOCATION record.

![image](https://cloud.githubusercontent.com/assets/5805454/13607303/768e2f00-e51d-11e5-8eaf-5e9971de0283.png)

The end result should be a simple SSRS report that can be exported to an Excel spreadsheet.

**Comment by taojun545** [comment]
Added new report "FSE List" in the FSE Reports page on dev.

The report will show all the locations with or without inspection. New SQL shows below:
`FROM            GIS_ADMIN.FSE_LOCATION AS L LEFT OUTER JOIN
                         GIS_ADMIN.FSE_INSPECTION AS I INNER JOIN
                             (SELECT        FSE_ID, MAX(FSE_INSPECTION_ID) AS INSP_ID
                               FROM            GIS_ADMIN.FSE_INSPECTION
                               GROUP BY FSE_ID) AS X ON X.FSE_ID = I.FSE_ID AND X.INSP_ID = I.FSE_INSPECTION_ID ON L.FSE_ID = I.FSE_ID`

**Comment by JMurk** [comment]
- For fields that are binary (i.e. 0,1), can you label them as "Yes" and "No", with 1 being Yes?
- there is a mispelling in one of the column headers.  Please update to say "GREASE DISPOSAL ADEQUATE"

![image](https://cloud.githubusercontent.com/assets/5805454/13650372/6530e06a-e610-11e5-8643-58a4ee19e27e.png)
- In the column header MAINT LOG UPTODATE, please make UPTODATE 3 words, UP TO DATE.
  ![image](https://cloud.githubusercontent.com/assets/5805454/13650420/994a309a-e610-11e5-800b-6447dd252749.png)

**Comment by taojun545** [comment]
Binary field updated, and both header description updated.

**Comment by JMurk** [comment]
Confirmed complete on dev, please push to prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
